#include <sys/ioctl.h>
#include <linux/if_tun.h>

int main(void) {

	int i;

	i = TUNSETNOCSUM;
	i = TUNSETDEBUG;
	i = TUNSETIFF;
	i = TUNSETPERSIST;
	i = TUNSETOWNER;
	i = TUNSETLINK;
	i = TUNSETGROUP;
	i = TUNGETFEATURES;
	i = TUNSETOFFLOAD;
	i = TUNSETTXFILTER;
	i = TUNGETIFF;
	i = TUNGETSNDBUF;
	i = TUNSETSNDBUF;
	i = TUNATTACHFILTER;
	i = TUNDETACHFILTER;
	i = TUNGETVNETHDRSZ;
	i = TUNSETVNETHDRSZ;
	i = TUNSETQUEUE;
	i = TUNSETIFINDEX;
	i = TUNGETFILTER;
	i = TUNSETVNETLE;
	i = TUNGETVNETLE;
	i = TUNSETVNETBE;
	i = TUNGETVNETBE;
	i = TUNSETSTEERINGEBPF;
	i = TUNSETFILTEREBPF;
	i = TUNSETCARRIER;
	i = TUNGETDEVNETNS;
	return 0;
}
